### PR TITLE
Updates to read me

### PR DESCRIPTION
**Pull request by Arjunica**

### CODE REVIEW

**Comment by galaxyonfire** [comment]
note that we need to add stuff into the Strengths and Weaknesses section

**Comment by QuinnWass** [comment]
Merge main

**Review by QuinnWass — CHANGES_REQUESTED** [review]
See comment above

**Review by galaxyonfire — DISMISSED** [review]
Just a reminder for us to fill out the Strengths and Weaknesses section

**Comment by Arjunica** [comment]
> Just a reminder for us to fill out the Strengths and Weaknesses section

I just did this

**Review by QuinnWass — APPROVED** [review]
Lgtm. I have a few readme updates. Will add those later and pr

**Pull request merged**
